<?php

namespace Tests;


use RKA\Session;
use SlimAuth\SlimAuthFacade;

class AuthTest extends BaseTests
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function shouldAuthGenerics() {
        $session = new Session();
        $adapter = new AuthTestAdapter('username', 'password');
        $auth = new SlimAuthFacade($adapter, $session);

        $auth->auth();
        $this->assertTrue($auth->isValid());

        $valueSession = $session->get('Slim3Auth');
        $this->assertEquals($valueSession['id'], 1010);
    }

    /**
     * @test
     */
    public function shouldAuthFailureGenerics() {
        $session = new Session();
        $adapter = new AuthTestAdapter('username', 'password1');
        $auth = new SlimAuthFacade($adapter, $session);

        $auth->auth();
        $this->assertTrue(!$auth->isValid());
    }

}